#!/bin/bash

echo "Deploying..."
sudo cp -a _/php/. /opt/lampp/htdocs/mipops/_/php/
sudo cp -a _/css/. /opt/lampp/htdocs/mipops/_/css/
sudo cp -a _/js/. /opt/lampp/htdocs/mipops/_/js/
sudo cp -a img/. /opt/lampp/htdocs/mipops/img/
sudo cp -a dox/. /opt/lampp/htdocs/mipops/dox/
sudo cp -a members-area/. /opt/lampp/htdocs/mipops/members-area/

sudo cp ./* /opt/lampp/htdocs/mipops
sudo chmod -R 755 /opt/lampp/htdocs/mipops
